#' Calculate the feasibility of a community S with n species
#'
#' @description This estimates the feasibility domain generated by an interaction matrix of n species. This measure typically decreases with dimension n. If the matrix has positive and negative values then feasibility will be within [0,0.5]; otherwise [0,1/2^n]---these bounds are important if the user aims to transform feasibility into a probability measure that assumes a uniform distribution of directions in parameter space.
#'
#' @param matA Numeric, an nxn interaction matrix A
#'
#' @param nt Numeric, number of replications to reduce numerical instabilities, default to 30
#' @param raw Logical, whether to return the raw feasibility or the normalized feasibility, default to TRUE
#'
#' @return Feasibility of all the n species in community S.
#'
#' Note Inside the main function raw and nt can be changed.
#' @importFrom mvtnorm pmvnorm
#' @importFrom magrittr %>%
#'
#' @export
#'
#' @examples
#' matA <- generate_inte_rand(4, 1, 1, "norm")  ## Generate a random interaction matrix of 4 species
#' nA <- nrow(matA) ## total number of species in the interaction matrix A
#' feasibility_community(matA) ## This is the feasibility of the community A with 4 species. This measure cannot be compared across communities with different number of species.
#' (feasibility_community(matA)) ^ (1 / nA) ## This is the species-specific feasibility of the community A with 4 species. This measure can be conmpared across communities with different number of species.

feasibility_community <- function(matA, nt = 30, raw = TRUE) {
  S <- nrow(matA)
  omega <- function(S, Sigma) {
    d <- pmvnorm(lower = rep(0, S), upper = rep(Inf, S), mean = rep(0, S), sigma = Sigma)
    return(d[1])
  }
  f <- function(m) class(try(solve(t(m) %*% m), silent = TRUE)) == "matrix"
  if (all(f(matA) == FALSE)) {
    return(0)
  }
  else {
    Sigma <- solve(t(matA) %*% matA)
    return(replicate(nt, omega(S, Sigma)) %>% mean())
  }
}
