#' Detect intersection vertex
#' @description function that computes all the extreme points generated that are generated by the intersections of the cones
#'
#' @param S matrix of the first set of vertexes
#' @param M matrix of the second set of vertexes
#' @importFrom utils combn
#' @importFrom pracma nullspace Rank
#'
#' @return a list with the extreme points that intersects these cones
intersection_vertex_detection <- function(S, M) {
  num <- ncol(S)
  if (num == 2) {
    return(list())
  } else {
    combination_S <- combn(seq_len(ncol(S)), 2)
    combination_M <- combn(seq_len(ncol(S)), (num - 1))
    Span_S <- norm2(S)
    Span_M <- norm2(M)

    border_M <- list()
    extreme_point_M <- list()
    for (i in seq_len(ncol(M))) {
      coeff_matrix <- matrix(0, ncol = num, nrow = num - 1)
      for (j in 1:(num - 1)) {
        coeff_matrix[j, ] <- Span_M[, combination_M[j, i]]
      }
      if (pracma::Rank(coeff_matrix) == (num - 1)) {
        border_M[[i]] <- pracma::nullspace(coeff_matrix)
      } else {
        stop("border_M_i is denegerated. Check the dimension.")
      }
      extreme_point_M[[i]] <- t(coeff_matrix)[1:(num - 1), 1:(num - 1)]
    }

    inside_face_detection <- function(extreme_point, test_vector) {
      lambda <- solve(extreme_point, test_vector)
      if (sum(lambda >= -1e-10) == length(lambda)) {
        return(1)
      } else {
        return(0)
      }
    }

    l <- 1
    intersection_vertex <- list()
    side <- c()
    for (i in seq_len(ncol(combination_S))) {
      vertex_1 <- Span_S[, combination_S[1, i]]
      vertex_2 <- Span_S[, combination_S[2, i]]
      for (j in seq_len(length(border_M))) {
        n1 <- sum(vertex_1 * border_M[[j]])
        n2 <- sum(vertex_2 * border_M[[j]])

        auxi <- n1 * n2
        if (auxi < -1e-10) {
          lambda <- n2 / (n2 - n1)
          possible <- lambda * vertex_1 + (1 - lambda) * vertex_2

          if (det(extreme_point_M[[j]]) != 0) {
            auxi2 <- inside_face_detection(extreme_point_M[[j]], possible[1:(num - 1)])
            if (auxi2 == 1) {
              intersection_vertex[[l]] <- possible
              side[l] <- j
              l <- l + 1
            }
          }
        }
      }
    }

    if (length(intersection_vertex) > 0) {
      for (i in seq_len(length(intersection_vertex))) {
        intersection_vertex[[i]] <- norm2(intersection_vertex[[i]])
      }
    }
  }

  return(intersection_vertex)
}